server:
  port: 8186
  servlet:
    context-path: /web-market-order
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
  kafka:
    consumer:
      group-id: 223
    bootstrap-servers: localhost:9092
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true


